name: CI

on:
  push:
  pull_request:

jobs:
  mock-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run WireMock tests only
        run: mvn -B -Dtest=AccuWeatherMockTests test

      - name: Upload surefire reports (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
